name: deploy 1.0

on:
    push:
        branches:
            -  develop

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: "20" # Укажите версию Node.js, если используется

            - name: Install dependencies
              run: npm install # Используйте команду, соответствующую вашему проекту

            - name: Build the project
              run: npm run build # Используйте команду, соответствующую вашему проекту

            - name: List build directory
              run: ls -la ./dist # Вывод содержимого директории dist для отладки

            - name: Deploy 1.0
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./dist # Директория, которая будет опубликована (замените на свою)
